apiVersion: v1
kind: Service
metadata:
  name: service-calculator
  namespace: namespace-calculator
spec:
  selector:
    app: app-calculator
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
